#!/bin/bash

cd buildGnu/
make clean; make; ../runTest.sh gnu $2
cd ../../streamMPI_sm/buildGnu/
make clean; make; ../runTest.sh gnu $2

cd ../../streamOpenMP/buildIntel/
source setIcc intel64; source setImpi
make clean; make; ../runTest.sh intel $2
cd ../../streamMPI_sm/buildIntel/
make clean; make; ../runTest.sh intel $2


cd ../../streamOpenMP/buildPgi/
source setPgi 18.1; source setPgiMpi 18.1
make clean; make; ../runTest.sh pgi $2
cd ../../streamMPI_sm/buildPgi/
make clean; make; ../runTest.sh pgi $2

